language: php

php:
 - '7.0'

cache:
  directories:
    - $HOME/.composer/cache

script:
 - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.clover
 - vendor/bin/php-cs-fixer fix . --rules=@Symfony --diff --dry-run -v

before_script:
 - composer require blablacar/redis-client "~1.0" --no-update
 - composer install

after_success:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
